image: node:10.16.0-stretch

stages:
  - test
  - version_dump
  - release
  - release_notify

test:
  stage: test
  only:
    refs:
      - merge_requests
    changes:
      - index.js
      - test/**/*

  before_script:
    - npm clean-install
  script:
    - npm test

version_dump:
  stage: version_dump
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: buildpack-deps:disco-scm

  before_script:
    - git config user.email admin@getto.systems
    - git config user.name getto
    - curl https://raw.githubusercontent.com/getto-systems/git-post/master/scripts/setup.sh | bash -s -- ./vendor/getto-systems
    - export PATH=$PATH:./vendor/getto-systems/git-post/bin
  script:
    - curl https://raw.githubusercontent.com/getto-systems/version-dump/master/bin/version_dump.sh | bash
    - curl https://raw.githubusercontent.com/getto-systems/version-dump/master/bin/request.sh | bash -s -- ./.release-version-message.sh

release:
  stage: release
  only:
    refs:
      - master@getto-systems-base/labo/node/getto-specification
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules

  before_script:
    - npm clean-install
  script:
    - npm test
    - curl https://raw.githubusercontent.com/getto-systems/version-dump/master/bin/push_tags.sh | bash
    - ./bin/publish.sh

release_success:
  stage: release_notify
  only:
    refs:
      - master@getto-systems-base/labo/node/getto-specification
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_success

  image: buildpack-deps:disco-curl

  before_script:
    - export channel=$SLACK_CHANNEL
  script:
    - curl https://raw.githubusercontent.com/getto-systems/psycher-getto/master/bin/notify-release.sh | bash -s -- -l $GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true success

release_failure:
  stage: release_notify
  only:
    refs:
      - master@getto-systems-base/labo/node/getto-specification
    changes:
      - .release-version
  except:
    refs:
      - triggers
      - schedules
  when: on_failure

  image: buildpack-deps:disco-curl

  before_script:
    - export channel=$SLACK_CHANNEL
  script:
    - curl https://raw.githubusercontent.com/getto-systems/psycher-getto/master/bin/notify-release.sh | bash -s -- -l $GETTO_PSYCHER_URL?$GETTO_PSYCHER_TOKEN=true failure
