stages:
  - test
  - build
  - release
  - notify

test:
  stage: test
  only:
    refs:
      - merge_requests
    changes:
      - index.js
      - test/**/*

  image: node:10.16.0-stretch

  before_script:
    - npm clean-install
  script:
    - npm test

build:
  stage: build
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: node:10.16.0-stretch

  before_script:
    - npm clean-install
  script:
    - npm test

release:
  stage: release
  only:
    refs:
      - triggers
    variables:
      - $RELEASE

  image: node:10.16.0-stretch

  variables:
    GIT_USER_NAME: getto
    GIT_USER_EMAIL: admin@getto.systems

  script:
    - curl https://raw.githubusercontent.com/getto-systems/version-dump/master/bin/version_dump.sh | bash
    - ./bin/push_tags.sh
    - ./bin/publish.sh

release_success:
  stage: notify
  only:
    refs:
      - triggers
    variables:
      - $RELEASE
  when: on_success

  image: buildpack-deps:disco-curl

  script:
    - ./bin/notify.sh success

release_failure:
  stage: notify
  only:
    refs:
      - triggers
    variables:
      - $RELEASE
  when: on_failure

  image: buildpack-deps:disco-curl

  script:
    - ./bin/notify.sh failure
